/**
 * @jest-environment node
 */
'use strict';

// Generative test for the async debug info tracking. Each seed builds a
// random Flight render over an adversarial async graph (hostile thenables,
// Promise subclasses, combinators, async generators, shared cached promises,
// interleaved concurrent renders) and snapshots the emitted debug info.
//
// Determinism: nothing in the workload races. Every async leaf parks its
// resolver with a driver, and a seeded loop fires them one at a time in a
// random order, running any real I/O (timers, file reads) to completion
// before the next pick, with seeded microtask/macrotask hops in between.
// Times are normalized and stacks are compared by function name only, so
// the snapshots are stable across machines and runs.
//
// The committed snapshots were generated by the async_hooks implementation
// of ReactFlightServerConfigDebugNode before it moved to v8.promiseHooks,
// so this doubles as a differential test between the two implementations:
// both must produce identical debug info for every seed.
//
// To debug a failing seed: FUZZ_TEST_SEED=<n> yarn test ReactFlightAsyncDebugInfoFuzz

import {patchSetImmediate} from '../../../../scripts/jest/patchSetImmediate';

import fs from 'fs';
import path from 'path';

let ReactServer;
let ReactServerDOMServer;
let ReactServerDOMClient;
let Stream;
let Random;
let getDebugInfo;

const NUM_SEEDS = 20;
const ONLY_SEED =
  process.env.FUZZ_TEST_SEED != null ? +process.env.FUZZ_TEST_SEED : null;

const streamOptions = {
  objectMode: true,
};

function filterStackFrame(filename, functionName) {
  return (
    !filename.startsWith('node:') &&
    !filename.includes('node_modules') &&
    // Filter out our own internal source code since it'll typically be in node_modules
    (!filename.includes('/packages/') || filename.includes('/__tests__/')) &&
    !filename.includes('/build/') &&
    !functionName.includes('internal_')
  );
}

describe('ReactFlightAsyncDebugInfoFuzz', () => {
  beforeEach(() => {
    jest.resetModules();
    jest.useRealTimers();
    patchSetImmediate();
    global.console = require('console');

    jest.mock('react', () => require('react/react.react-server'));
    jest.mock('react-server-dom-webpack/server', () =>
      jest.requireActual('react-server-dom-webpack/server.node'),
    );
    ReactServer = require('react');
    ReactServerDOMServer = require('react-server-dom-webpack/server');

    jest.resetModules();
    jest.useRealTimers();
    patchSetImmediate();

    __unmockReact();
    jest.unmock('react-server-dom-webpack/server');
    jest.mock('react-server-dom-webpack/client', () =>
      jest.requireActual('react-server-dom-webpack/client.node'),
    );

    ReactServerDOMClient = require('react-server-dom-webpack/client');
    Stream = require('stream');
    Random = require('random-seed');

    getDebugInfo = require('internal-test-utils').getDebugInfo.bind(null, {
      ignoreProps: true,
      ignoreRscStreamInfo: true,
      useFixedTime: true,
      useV8Stack: true,
    });
  });

  jest.setTimeout(60000);

  // TODO: Remove this once the Flight client stops turning rejected awaited
  // values into handler-less rejected chunks during stream processing. They
  // reject before any test code can attach a handler, so Node's default
  // unhandled-rejections mode would kill the process. Collect them instead,
  // but only tolerate the rejections the workload itself created.
  let unhandled = [];
  const onUnhandled = reason => {
    unhandled.push(reason);
  };
  beforeEach(() => {
    unhandled = [];
    process.on('unhandledRejection', onUnhandled);
  });
  afterEach(() => {
    process.removeListener('unhandledRejection', onUnhandled);
    unhandled.forEach(reason => {
      const message =
        reason && reason.message ? reason.message : String(reason);
      if (!/^rejected v\d+$/.test(message)) {
        throw new Error('unexpected unhandled rejection: ' + message);
      }
    });
  });

  function finishLoadingStream(readable) {
    return new Promise(resolve => {
      if (readable.readableEnded) {
        resolve();
      } else {
        readable.on('end', () => resolve());
      }
    });
  }

  // Real I/O used by fired leaves. The driver awaits these to completion one
  // at a time so their real-world latency can never reorder anything.
  function fuzzDelay(ms) {
    return new Promise(resolve => {
      setTimeout(resolve, ms);
    });
  }
  function fuzzRead() {
    return new Promise((resolve, reject) => {
      fs.readFile(path.join(__dirname, '../ReactFlightAsyncSequence.js'), r =>
        r ? reject(r) : resolve(),
      );
    });
  }

  class FuzzPromise extends Promise {}

  function createProgram(rand) {
    // Everything the program allocates is retained until the test ends so
    // that GC can never make a WeakRef-dependent field disappear from the
    // output of one run but not another.
    const retained = [];
    const pending = []; // [{fire}] parked leaf resolvers
    let nextValue = 0;

    function retain(x) {
      retained.push(x);
      return x;
    }

    // A leaf promise whose resolution is parked with the driver. When fired
    // it performs one unit of real I/O (so IO nodes exist and get awaited)
    // and then settles.
    function leaf(rejects) {
      const id = 'v' + nextValue++;
      const useTimer = rand.intBetween(0, 1) === 0;
      const promise = new Promise((resolve, reject) => {
        pending.push({
          fire: async function fireLeaf() {
            if (useTimer) {
              await fuzzDelay(1);
            } else {
              await fuzzRead();
            }
            if (rejects) {
              reject(new Error('rejected ' + id));
            } else {
              resolve(id);
            }
          },
        });
      });
      if (rejects) {
        // The driver may fire this before a consumer has attached its
        // handler; mark it handled so that can't crash the run.
        retain(promise.catch(function ignoreUnhandled() {}));
      }
      return retain(promise);
    }

    // Hostile thenables. All of them eventually resolve deterministically;
    // the interesting part is how they call (or abuse) resolve/reject.
    function thenableOf(node, kind) {
      if (kind === 0) {
        // resolves synchronously when awaited
        return {
          then(resolve) {
            resolve(retain(node));
          },
        };
      }
      if (kind === 1) {
        // calls resolve twice
        return {
          then(resolve) {
            resolve(retain(node));
            resolve('ignored double resolve');
          },
        };
      }
      if (kind === 2) {
        // throws after resolving
        return {
          then(resolve) {
            resolve(retain(node));
            throw new Error('thrown after resolve');
          },
        };
      }
      if (kind === 3) {
        // rejects after resolving
        return {
          then(resolve, reject) {
            resolve(retain(node));
            reject(new Error('ignored late reject'));
          },
        };
      }
      // resolution parked with the driver
      return {
        then(resolve) {
          pending.push({
            fire: async function fireThenable() {
              resolve(retain(node));
            },
          });
        },
      };
    }

    // A proxy in front of a thenable, like our own ClientReference proxies
    // which throw for most property accesses.
    function proxyThenable(node) {
      const target = thenableOf(node, 4);
      return new Proxy(target, {
        get(t, key) {
          if (
            key === 'then' ||
            key === 'status' ||
            key === 'value' ||
            key === 'reason' ||
            key === 'constructor' ||
            typeof key === 'symbol'
          ) {
            return t[key];
          }
          throw new Error('touched forbidden key ' + String(key));
        },
        set(t, key, v) {
          t[key] = v;
          return true;
        },
      });
    }

    // Random async value graph. Rejecting branches are always caught by the
    // construct that created them so every graph settles successfully.
    function genNode(depth) {
      const roll = rand.intBetween(0, depth >= 4 ? 4 : 13);
      switch (roll) {
        case 0:
          return leaf(false);
        case 1:
          return retain(Promise.resolve('sync' + nextValue++));
        case 2:
          return retain(
            Promise.resolve(
              retain(Promise.resolve(retain(Promise.resolve('deep')))),
            ),
          );
        case 3:
          return thenableOf('t' + nextValue++, rand.intBetween(0, 4));
        case 4: {
          // rejecting leaf, caught right here
          return retain(
            leaf(true)[rand.intBetween(0, 1) === 0 ? 'catch' : 'then'](
              function caughtLeaf(x) {
                return 'caught:' + (x && x.message ? x.message : x);
              },
              function caughtLeafRejection(x) {
                return 'caught:' + x.message;
              },
            ),
          );
        }
        case 5: {
          const inner = genNode(depth + 1);
          return retain(
            Promise.resolve(inner).then(function chained(x) {
              return rand.intBetween(0, 1) === 0 ? genNode(depth + 1) : x;
            }),
          );
        }
        case 6: {
          const parts = [];
          const n = rand.intBetween(2, 3);
          for (let i = 0; i < n; i++) {
            parts.push(genNode(depth + 1));
          }
          return retain(Promise.all(parts));
        }
        case 7: {
          const parts = [genNode(depth + 1), genNode(depth + 1)];
          return retain(Promise.race(parts));
        }
        case 8: {
          const parts = [
            rand.intBetween(0, 1) === 0 ? leaf(true) : genNode(depth + 1),
            genNode(depth + 1),
          ];
          return retain(
            Promise.allSettled(parts).then(function settledSummary(rs) {
              let out = '';
              rs.forEach(r => {
                out += r.status + ';';
              });
              return out;
            }),
          );
        }
        case 9: {
          const inner = genNode(depth + 1);
          return retain(
            (async function nestedAsync() {
              if (rand.intBetween(0, 1) === 0) {
                await retain(Promise.resolve(null));
              }
              const v = await inner;
              return v;
            })(),
          );
        }
        case 10: {
          // async generator, consumed partially
          const items = [genNode(depth + 1), genNode(depth + 1)];
          const take = rand.intBetween(1, 2);
          const fuzzGenerator = async function* fuzzGenerator() {
            for (let i = 0; i < items.length; i++) {
              yield await items[i];
            }
          };
          return retain(
            (async function consumeGenerator() {
              const iterator = fuzzGenerator();
              let out = '';
              for (let i = 0; i < take; i++) {
                const step = await iterator.next();
                if (step.done) {
                  break;
                }
                out += String(step.value) + '|';
              }
              if (iterator.return) {
                await iterator.return();
              }
              return out;
            })(),
          );
        }
        case 11:
          return retain(
            new FuzzPromise(resolve => {
              pending.push({
                fire: async function fireSubclass() {
                  resolve('sub' + nextValue++);
                },
              });
            }),
          );
        case 12:
          return proxyThenable('p' + nextValue++);
        default: {
          const inner = genNode(depth + 1);
          return retain(
            Promise.resolve(inner).finally(function finallyBlock() {}),
          );
        }
      }
    }

    return {retained, pending, genNode, leaf, retain};
  }

  async function drive(rand, program, doneRef) {
    // Fire parked resolvers one at a time in seeded-random order with seeded
    // scheduling hops in between. Each fire is awaited to completion so real
    // I/O latency can never reorder events between two runs.
    let iterations = 0;
    while (!doneRef.done || program.pending.length > 0) {
      if (iterations++ > 10000) {
        throw new Error('driver did not converge');
      }
      if (program.pending.length > 0) {
        const idx = rand.intBetween(0, program.pending.length - 1);
        const entry = program.pending.splice(idx, 1)[0];
        await entry.fire();
      }
      const hops = rand.intBetween(1, 3);
      for (let i = 0; i < hops; i++) {
        switch (rand.intBetween(0, 2)) {
          case 0:
            await null;
            break;
          case 1:
            await new Promise(resolve => setImmediate(resolve));
            break;
          default:
            await new Promise(resolve => process.nextTick(resolve));
            break;
        }
      }
    }
  }

  // Collect debug info from the resolved client tree, in traversal order.
  function collectDebugInfo(root) {
    const out = [];
    const visited = new Set();
    const queue = [root];
    let budget = 500;
    while (queue.length > 0 && budget-- > 0) {
      const value = queue.shift();
      if (value === null || typeof value !== 'object' || visited.has(value)) {
        continue;
      }
      visited.add(value);
      if (value._debugInfo) {
        // Rejected awaited values arrive as rejected debug chunks; touch them
        // with a handler first so normalization's bare .then() can't turn
        // them into an unhandled rejection.
        value._debugInfo.forEach(function markHandled(entry) {
          if (entry && entry.owner) {
            markHandled(entry.owner);
          }
          if (
            entry &&
            entry.awaited &&
            entry.awaited.value &&
            typeof entry.awaited.value.then === 'function'
          ) {
            entry.awaited.value.then(
              function ignoreValue() {},
              function ignoreReason() {},
            );
          }
        });
        out.push(getDebugInfo(value));
      }
      if (Array.isArray(value)) {
        value.forEach(v => queue.push(v));
      } else if (value.$$typeof === Symbol.for('react.element')) {
        queue.push(value.props.children);
        if (value.props.data != null) {
          queue.push(value.props.data);
        }
      } else if (value.$$typeof === Symbol.for('react.transitional.element')) {
        queue.push(value.props.children);
        if (value.props.data != null) {
          queue.push(value.props.data);
        }
      } else if (typeof value.then === 'function') {
        if (value.status === 'fulfilled') {
          queue.push(value.value);
        }
      }
    }
    return out;
  }

  function summarize(value) {
    if (value === null || value === undefined) {
      return String(value);
    }
    if (typeof value === 'string' || typeof value === 'number') {
      return String(value);
    }
    if (Array.isArray(value)) {
      return '[' + value.map(summarize).join(',') + ']';
    }
    if (
      value.$$typeof === Symbol.for('react.element') ||
      value.$$typeof === Symbol.for('react.transitional.element')
    ) {
      const name =
        typeof value.type === 'string'
          ? value.type
          : value.type.name || 'anonymous';
      return (
        '<' + name + '>' + summarize(value.props.children) + '</' + name + '>'
      );
    }
    if (typeof value.then === 'function') {
      return value.status === 'fulfilled'
        ? 'promise(' + summarize(value.value) + ')'
        : 'promise(' + value.status + ')';
    }
    return Object.prototype.toString.call(value);
  }

  function buildComponents(rand, program) {
    // Shared cached data: some entries resolve before the render starts,
    // some resolve mid-render, and several components dedupe on them
    // through ReactServer.cache().
    const pool = [];
    for (let i = 0; i < 3; i++) {
      pool.push(program.leaf(false));
    }
    const cachedFetch = ReactServer.cache(async function cachedFetch(key) {
      const v = await pool[key];
      return 'pool:' + key + ':' + v;
    });

    let componentId = 0;

    // use() in a sync component: suspends and replays the component, which
    // re-executes everything before it deterministically.
    function makeSyncUseComponent() {
      const name = 'FuzzUse' + componentId++;
      // TODO: use() the raw node once hostile thenables survive it: use()
      // instruments the thenable it receives, and one that settles more than
      // once makes the debug channel emit twice for the same chunk. The
      // graph behind the native promise stays adversarial in the meantime.
      const node = program.retain(Promise.resolve(program.genNode(2)));
      const Component = {
        [name]: function () {
          const v = ReactServer.use(node);
          return name + ':' + String(v);
        },
      }[name];
      return Component;
    }

    function makeComponent(depth) {
      const name = 'Fuzz' + componentId++;
      const awaitsCatch = rand.intBetween(0, 3) === 0;
      const nodes = [];
      const nAwaits = rand.intBetween(1, 2);
      for (let i = 0; i < nAwaits; i++) {
        nodes.push(
          awaitsCatch && i === 0 ? program.leaf(true) : program.genNode(0),
        );
      }
      const useCache = rand.intBetween(0, 2) === 0;
      const cacheKey = rand.intBetween(0, pool.length - 1);
      const children = [];
      if (depth < 2) {
        const nChildren = rand.intBetween(0, 2);
        for (let i = 0; i < nChildren; i++) {
          children.push(
            rand.intBetween(0, 3) === 0
              ? makeSyncUseComponent()
              : makeComponent(depth + 1),
          );
        }
      }
      const passPromiseProp = depth < 2 && rand.intBetween(0, 2) === 0;
      // TODO: Pass the raw node once serializing a userland thenable that
      // settles more than once no longer double-emits its row and crashes
      // the Flight client (controller.enqueueModel is not a function).
      // Promise.resolve() gives it settle-once semantics in the meantime.
      const propPromise = passPromiseProp
        ? program.retain(Promise.resolve(program.genNode(0)))
        : null;

      const Component = {
        [name]: async function (props) {
          let out = name + ':';
          for (let i = 0; i < nodes.length; i++) {
            if (awaitsCatch && i === 0) {
              try {
                out += await nodes[i];
              } catch (x) {
                out += 'caught:' + x.message;
              }
            } else {
              out += String(await nodes[i]);
            }
            out += ';';
          }
          if (useCache) {
            out += await cachedFetch(cacheKey);
          }
          if (props && props.data != null) {
            out += '/data:' + String(await props.data);
          }
          const childElements = children.map((Child, i) =>
            ReactServer.createElement(Child, {
              key: i,
              data: i === 0 ? propPromise : null,
            }),
          );
          return [out, childElements];
        },
      }[name];
      return Component;
    }

    return {makeComponent, pool};
  }

  async function runSeed(seed) {
    const rand = Random.create('flight-fuzz-' + seed);
    const program = createProgram(rand);
    const {makeComponent, pool} = buildComponents(rand, program);

    // Resolve a seeded subset of the shared pool before rendering starts so
    // some awaits hit promises that settled before the request existed.
    const preResolve = rand.intBetween(0, pool.length - 1);
    for (let i = 0; i < preResolve; i++) {
      const entry = program.pending.splice(0, 1)[0];
      await entry.fire();
      await pool[i];
    }

    const concurrentRenders = rand.intBetween(0, 3) === 0 ? 2 : 1;
    const roots = [];
    for (let i = 0; i < concurrentRenders; i++) {
      roots.push(makeComponent(0));
    }

    const results = [];
    const readables = [];
    roots.forEach(Root => {
      const stream = ReactServerDOMServer.renderToPipeableStream(
        ReactServer.createElement(Root, null),
        {},
        {filterStackFrame},
      );
      const readable = new Stream.PassThrough(streamOptions);
      results.push(
        ReactServerDOMClient.createFromNodeStream(readable, {
          moduleMap: {},
          moduleLoading: {},
        }),
      );
      readables.push(readable);
      stream.pipe(readable);
    });

    const doneRef = {done: false};
    const allDone = Promise.all([
      // Roots are constructed to never reject, but if one does we still need
      // the driver to terminate so the failure surfaces as a value diff.
      Promise.all(
        results.map(r =>
          r.then(
            v => v,
            x => x,
          ),
        ),
      ),
      Promise.all(readables.map(finishLoadingStream)),
    ]).then(() => {
      doneRef.done = true;
    });

    await drive(rand, program, doneRef);
    await allDone;

    const output = [];
    for (let i = 0; i < results.length; i++) {
      let value;
      try {
        value = await results[i];
      } catch (x) {
        output.push({value: 'root rejected: ' + x.message, debugInfo: []});
        continue;
      }
      output.push({
        value: summarize(value),
        debugInfo: collectDebugInfo(value),
      });
    }
    return output;
  }

  for (let seed = 0; seed < NUM_SEEDS; seed++) {
    if (ONLY_SEED !== null && seed !== ONLY_SEED) {
      continue;
    }
    it(`produces stable async debug info (seed ${seed})`, async () => {
      const output = await runSeed(seed);
      if (
        __DEV__ &&
        gate(
          flags =>
            flags.enableComponentPerformanceTrack && flags.enableAsyncDebugInfo,
        )
      ) {
        expect(output).toMatchSnapshot();
      }
    });
  }
});
